### ISSUE TITLE
fslanat, poor segmentation leads to silent failures in brain volume estimation, breaking aggregator

### ISSUE THREAD

**Issue by psadil** [a2cps/mri_imaging_pipeline#324]
The logs (tapis and fslanat) for the fslanat job that included NS10932V3 don't indicate any failure, but the volumes are missing from the T1_vols.txt file

```shell
❯ cat T1_vols.txt 
Scaling factor from T1 to MNI (using skull-constrained linear registration) = 0.759238
Brain volume in mm^3 (native/original space) = 
Brain volume in mm^3 (normalised to MNI) =
```

fsl estimates volume here: https://git.fmrib.ox.ac.uk/fsl/misc_scripts/-/blob/master/fsl_anat?ref_type=heads#L548-556

> ```shell
>     ugrey=`$FSLDIR/bin/fslstats ${T1}_fast_pve_1 -m -v | awk '{ print $1 * $3 }'`;
>     ngrey=`echo "$ugrey * $vscale" | bc -l`;
>     uwhite=`$FSLDIR/bin/fslstats ${T1}_fast_pve_2 -m -v | awk '{ print $1 * $3 }'`;
>     nwhite=`echo "$uwhite * $vscale" | bc -l`;
>     ubrain=`echo "$ugrey + $uwhite" | bc -l`;
>     nbrain=`echo "$ngrey + $nwhite" | bc -l`;
>     echo "Scaling factor from ${T1} to MNI (using skull-constrained linear registration) = $vscale" > ${T1}_vols.txt
>     echo "Brain volume in mm^3 (native/original space) = $ubrain" >> ${T1}_vols.txt
>     echo "Brain volume in mm^3 (normalised to MNI) = $nbrain" >> ${T1}_vols.txt
> 
> ```

The unnormalized white matter is calculated as being very large (leading to scientific notation)

```shell
❯ fslstats T1_fast_pve_2 -m -v | awk '{ print $1 * $3 }'
1.5744e+06
``` 
which confuses `bc`

```shell
❯ echo "$ugrey + $uwhite" | bc -l

Parse error: bad character '+'
    <stdin>:1
```

When the aggregation_app uses `biomarker-extractor` to extract fsl's estimate of volume (https://github.com/a2cps/biomarker-extractor/blob/33f97d431955c8c9bf6b3cb7af0beff08c4090e8/src/biomarkers/models/fslanat.py#L261-L265)

an exception is raised

```python
Traceback (most recent call last):
  File "/opt/tapis/stage.py", line 516, in <module>
    main(
  File "/opt/tapis/stage.py", line 501, in main
    fslanat_wf.make_toplevel(outdir=outroot / "fslanat")
  File "/opt/tapis/fslanat_wf.py", line 42, in make_toplevel
    _get_all_volumes(outdir).to_csv(outdir / "fslanat.tsv", sep="\t", index=False)
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tapis/fslanat_wf.py", line 22, in _get_all_volumes
    volumes.append(_get_fslanat_table(src).assign(sub=sub, ses=ses))
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tapis/fslanat_wf.py", line 13, in _get_fslanat_table
    brain = result.get_t1volumes()
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/biomarkers/models/fslanat.py", line 280, in get_t1volumes
    re.findall(r" \d+", lines[1])[0]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

relevant logs: /corral-secure/projects/A2CPS/shared/a2cpsadmin/jobs/e42f90bb-be15-495d-bfeb-beefe366b9a5-007

**Comment by psadil** [comment]
Nothing is obviously wrong with the raw data

<img width="1354" alt="Screenshot 2024-11-08 at 12 53 42" src="https://github.com/user-attachments/assets/b81b51b4-1c4f-42cf-90d0-e2921c603af2">


But by the time of segmentation something is off (T1_fast_pve_2.nii.gz )
<img width="1354" alt="Screenshot 2024-11-08 at 12 52 50" src="https://github.com/user-attachments/assets/a2d661fe-709f-47df-b778-5242f9ba8bda">
